### ISSUE TITLE
init.el fails to launch

### ISSUE THREAD

**Issue by GiulioCentorame** [MatthewZMD/.emacs.d#34] opened 2020-05-26 16:44 UTC
**Describe the bug**
I have noticed that this error message started popping up from time to time when launched, most likely after a package update:

`Warning (initialization): An error occurred while loading ‘/home/giuliocentorame/.emacs.d/init.el’:

error: Keyword argument :init-fn not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. `

and Emacs doesn't launch the init.el at all.

`--debug-init` reports the following:

`Debugger entered--Lisp error: (error "Keyword argument :init-fn not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)")
  signal(error ("Keyword argument :init-fn not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)"))
  error("Keyword argument %s not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)" :init-fn)
  ivy-configure(swiper-isearch :occur swiper-occur :init-fn swiper--isearch-init :update-fn auto :unwind-fn swiper--isearch-unwind :format-fn swiper-isearch-format-function)
  require(swiper)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\304\305\306\307\310\311\312\313&\007\207" [require swiper compile dired custom-declare-group counsel nil "Completion functions using Ivy." :group matching :prefix "counsel-"] 8)
  require(counsel nil nil)
  eval-buffer(#<buffer  *load*-567389> nil "/home/user/.emacs.d/elisp/init-search.el" nil t)  ; Reading at buffer position 2379
  load-with-code-conversion("/home/user/.emacs.d/elisp/init-search.el" "/home/giuliocentorame/.emacs.d/elisp/init-search.el" nil t)
  require(init-search)
  eval-buffer(#<buffer  *load*> nil "/home/user/.emacs.d/init.el" nil t)  ; Reading at buffer position 4295
  load-with-code-conversion("/home/user/.emacs.d/init.el" "/home/giuliocentorame/.emacs.d/init.el" t t)
  load("/home/giuliocentorame/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1df6a1>)()
  command-line()
  normal-top-level()
`

**To Reproduce**

- Launch Emacs
- "y" when requested to update the packages
- Keep Emacs in the background

**Expected behavior**
Launching normally.

**Versions (please complete the following information):**
 - OS and/or Distros: Linux Manjaro
 - GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

**Comment by MatthewZMD** [comment] 2020-05-26 17:14
This is weird, I have never seen this error before. I also have Manjaro.

Can you try to pinpoint the package or the file that's causing the error? Maybe start by commenting out half of the in init.el and so on?

**Comment by GiulioCentorame** [comment] 2020-05-26 17:22
Did a couple of tries and commenting out `(require 'init-search)` allows to load the init.el file correctly (minus some bytecomp errors)

**Comment by GiulioCentorame** [comment] 2020-05-26 17:33
I tried to comment/uncomment parts of init-search.el and I think the culprit is the loading script for ivy, it works without it

**Comment by MatthewZMD** [comment] 2020-05-27 00:42
I think you should create an issue at ivy regarding this, I cannot reproduce at all

**Comment by MatthewZMD** [comment] 2020-07-07 22:54
Closed as unreproducible

**Closed by MatthewZMD** 2020-07-07 22:54 UTC
